cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/237142071300/trial_queue.fifo
    region:
      auto: false
      static: us-east-1
    stack:
      auto: false
